services:
  app:
    build: .
    container_name: shortener-app
    restart: always
    env_file: .env
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Admin123.
      - DB_NAME=shortenerdb
      - DB_SSLMODE=disable
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:14.1
    container_name: postgres
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin123.
      - POSTGRES_DB=shortenerdb
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: {}
