services:
  app:
    build: .
    container_name: shortener-app
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
  db:
    image: postgres:14.1
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: {}
